/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.inicio;

/**
 *
 * @author maico
 */
public class materiasp extends javax.swing.JFrame {

   private int idUsuario;
    private String nombre;
    public materiasp(String nombre, int idUsuario) {
        this.nombre = nombre ; 
       this.idUsuario = idUsuario;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        calmultivariado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        estructurasinfo = new javax.swing.JLabel();
        fisica3 = new javax.swing.JLabel();
        arquitectura = new javax.swing.JLabel();
        fundamentosadmi = new javax.swing.JLabel();
        ingles2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        programacion1 = new javax.swing.JLabel();
        Caldiferencial = new javax.swing.JLabel();
        fisica1 = new javax.swing.JLabel();
        argumentativo = new javax.swing.JLabel();
        estadistica = new javax.swing.JLabel();
        pensamientocri1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        programacion2 = new javax.swing.JLabel();
        calintegral = new javax.swing.JLabel();
        ciudadania = new javax.swing.JLabel();
        fisica2 = new javax.swing.JLabel();
        ingles1 = new javax.swing.JLabel();
        comunicacion2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        algebralineal = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        pensamientoal = new javax.swing.JLabel();
        fundamentoselectronica = new javax.swing.JLabel();
        fundamentosing = new javax.swing.JLabel();
        discretas = new javax.swing.JLabel();
        pensamientosistemico = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        ecuadiferenciales = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        ingsoftware = new javax.swing.JLabel();
        operativos = new javax.swing.JLabel();
        sisinformacion = new javax.swing.JLabel();
        basesdedatos = new javax.swing.JLabel();
        planeacionestrategica = new javax.swing.JLabel();
        ingles3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        matespeciales = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        ingsoftware2 = new javax.swing.JLabel();
        comudatos = new javax.swing.JLabel();
        networking = new javax.swing.JLabel();
        catedra = new javax.swing.JLabel();
        emprendimiento = new javax.swing.JLabel();
        ingles4 = new javax.swing.JLabel();
        innovacionpro = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        analisisnum = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        operativa = new javax.swing.JLabel();
        redesycomunicacion = new javax.swing.JLabel();
        cienciadedtaos = new javax.swing.JLabel();
        seginformatica = new javax.swing.JLabel();
        cienciainnovacionmarco = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        artificial = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        automatas = new javax.swing.JLabel();
        profundizacion1 = new javax.swing.JLabel();
        cienciainnovacioncampo = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        gerencia = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        modelacion = new javax.swing.JLabel();
        profundizacion2 = new javax.swing.JLabel();
        opciongrado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        calmultivariado.setText("Cálculo multivario");
        calmultivariado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calmultivariadoMouseClicked(evt);
            }
        });

        jLabel2.setText("SEMESTRE 4");

        estructurasinfo.setText("Estructuras de información");

        fisica3.setText("Fisica III (electricidad y magnetismo)");
        fisica3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fisica3MouseClicked(evt);
            }
        });

        arquitectura.setText("Arquitectura de computadores");

        fundamentosadmi.setText("Fundamentos administrativos");

        ingles2.setText("Ingles II");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(calmultivariado)
                    .addComponent(estructurasinfo)
                    .addComponent(fisica3)
                    .addComponent(arquitectura)
                    .addComponent(fundamentosadmi)
                    .addComponent(ingles2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calmultivariado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estructurasinfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fisica3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(arquitectura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fundamentosadmi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ingles2)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel8.setText("SEMESTRE 2");

        programacion1.setText("Programación I");

        Caldiferencial.setText("Cálculo diferencial");

        fisica1.setText("Fisica I (Mecánica)");

        argumentativo.setText("Razonamiento argumentativo ");

        estadistica.setText("Estadística, probabilidad e inferencia");

        pensamientocri1.setText("Comunicación y pensamiento crítico I");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(programacion1)
                            .addComponent(jLabel8)
                            .addComponent(Caldiferencial)
                            .addComponent(argumentativo))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fisica1)
                            .addComponent(estadistica)
                            .addComponent(pensamientocri1))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Caldiferencial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(programacion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(argumentativo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fisica1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estadistica)
                .addGap(5, 5, 5)
                .addComponent(pensamientocri1)
                .addContainerGap())
        );

        jLabel15.setText("SEMESTRE 3");

        programacion2.setText("Programación II");

        calintegral.setText("Cálculo integral");

        ciudadania.setText("ciudadania sel siglo XXI");

        fisica2.setText("Física II (optica y ondas)");

        ingles1.setText("Ingles I");

        comunicacion2.setText("Comunicación y pensamiento crítico II");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(programacion2)
                            .addComponent(jLabel15)
                            .addComponent(calintegral)
                            .addComponent(fisica2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ciudadania)
                            .addComponent(ingles1)
                            .addComponent(comunicacion2))
                        .addGap(0, 37, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calintegral)
                .addGap(18, 18, 18)
                .addComponent(programacion2)
                .addGap(18, 18, 18)
                .addComponent(fisica2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ciudadania)
                .addGap(18, 18, 18)
                .addComponent(ingles1)
                .addGap(5, 5, 5)
                .addComponent(comunicacion2)
                .addContainerGap())
        );

        algebralineal.setText("Álgebra lineal");
        algebralineal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                algebralinealMouseClicked(evt);
            }
        });

        jLabel23.setText("SEMESTRE 1");

        pensamientoal.setText("Pensamiento algorítmico");
        pensamientoal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pensamientoalMouseClicked(evt);
            }
        });

        fundamentoselectronica.setText("Fundamentos de electrónica");
        fundamentoselectronica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fundamentoselectronicaMouseClicked(evt);
            }
        });

        fundamentosing.setText("Fundamentos de ingeniería");
        fundamentosing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fundamentosingMouseClicked(evt);
            }
        });

        discretas.setText("Matemáticas discretas");
        discretas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                discretasMouseClicked(evt);
            }
        });

        pensamientosistemico.setText("Pensamiento sistémico y automatización");
        pensamientosistemico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pensamientosistemicoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(algebralineal)
                    .addComponent(pensamientoal)
                    .addComponent(fundamentoselectronica)
                    .addComponent(fundamentosing)
                    .addComponent(discretas)
                    .addComponent(pensamientosistemico))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(algebralineal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pensamientoal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fundamentoselectronica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fundamentosing)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(discretas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pensamientosistemico)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        ecuadiferenciales.setText("Ecuaciones diferenciales");
        ecuadiferenciales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ecuadiferencialesMouseClicked(evt);
            }
        });

        jLabel30.setText("SEMESTRE 5");

        ingsoftware.setText("Ingenieria de software I");

        operativos.setText("Sistemas operativos");

        sisinformacion.setText("Sistemas de información");

        basesdedatos.setText("Bases de datos ");

        planeacionestrategica.setText("Planeacion estrategica");

        ingles3.setText("Ingles III");
        ingles3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingles3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(ecuadiferenciales)
                    .addComponent(ingsoftware)
                    .addComponent(operativos)
                    .addComponent(sisinformacion)
                    .addComponent(basesdedatos)
                    .addComponent(planeacionestrategica)
                    .addComponent(ingles3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ecuadiferenciales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ingsoftware)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(operativos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sisinformacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(basesdedatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(planeacionestrategica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ingles3))
        );

        matespeciales.setText("Matematicas especiales");
        matespeciales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                matespecialesMouseClicked(evt);
            }
        });

        jLabel37.setText("SEMESTRE 6");

        ingsoftware2.setText("Ingenieria de software II");

        comudatos.setText("Comunicacion de datos ");

        networking.setText("Networking");

        catedra.setText("Catedra generacion de XXI  ");

        emprendimiento.setText("Emprendimiento");

        ingles4.setText("Ingles IV");

        innovacionpro.setText("Ciencia tecnologia e innovacion(problemas y formulacion");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addComponent(matespeciales)
                    .addComponent(ingsoftware2)
                    .addComponent(comudatos)
                    .addComponent(networking)
                    .addComponent(emprendimiento)
                    .addComponent(ingles4)
                    .addComponent(catedra)
                    .addComponent(innovacionpro))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(matespeciales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ingsoftware2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comudatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(networking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(catedra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(innovacionpro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emprendimiento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ingles4)
                .addContainerGap())
        );

        analisisnum.setText("Analisis numerico");
        analisisnum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                analisisnumMouseClicked(evt);
            }
        });

        jLabel46.setText("SEMESTRE 7");

        operativa.setText("operativa");

        redesycomunicacion.setText("Redes y comunicacion");

        cienciadedtaos.setText("ciencia de datos ");

        seginformatica.setText("Seguridad informatica");

        cienciainnovacionmarco.setText("Ciencia tecnologia e innovacion(marco de referencia)");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel46)
                    .addComponent(analisisnum)
                    .addComponent(redesycomunicacion)
                    .addComponent(cienciadedtaos)
                    .addComponent(seginformatica)
                    .addComponent(cienciainnovacionmarco)
                    .addComponent(operativa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel46)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(analisisnum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(operativa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(redesycomunicacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cienciadedtaos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seginformatica, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cienciainnovacionmarco)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        artificial.setText("Inteligencia artificial");
        artificial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                artificialMouseClicked(evt);
            }
        });

        jLabel53.setText("SEMESTRE 8");

        automatas.setText("lenguajes automatas");

        profundizacion1.setText("profundizacion I");

        cienciainnovacioncampo.setText("Ciencia tecnologia e innovacion(trabajo de campo)");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel53)
                    .addComponent(artificial)
                    .addComponent(automatas)
                    .addComponent(profundizacion1)
                    .addComponent(cienciainnovacioncampo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel53)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(artificial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(automatas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profundizacion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cienciainnovacioncampo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gerencia.setText("Gerencia de proyectos ");
        gerencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gerenciaMouseClicked(evt);
            }
        });

        jLabel57.setText("SEMESTRE 9");

        modelacion.setText("modelacion");

        profundizacion2.setText("profundizacion Il");

        opciongrado.setText("Opcion de grado");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel57)
                    .addComponent(gerencia)
                    .addComponent(modelacion)
                    .addComponent(profundizacion2)
                    .addComponent(opciongrado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel57)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gerencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modelacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profundizacion2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opciongrado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calmultivariadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calmultivariadoMouseClicked
        InfoMateria info = new InfoMateria("Calculo multivariado ",this.nombre,this.idUsuario);
        info.setVisible(true);
    }//GEN-LAST:event_calmultivariadoMouseClicked

    private void algebralinealMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_algebralinealMouseClicked
        InfoMateria info = new InfoMateria("Algebra lineal ",this.nombre,this.idUsuario);
        info.setVisible(true);
    }//GEN-LAST:event_algebralinealMouseClicked

    private void pensamientoalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pensamientoalMouseClicked
        InfoMateria info = new InfoMateria("Pensamiento algoritmico ",this.nombre,this.idUsuario);
        info.setVisible(true);
    }//GEN-LAST:event_pensamientoalMouseClicked

    private void fundamentoselectronicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fundamentoselectronicaMouseClicked
        InfoMateria info = new InfoMateria("Fundamrntos de electronica",this.nombre,this.idUsuario);
        info.setVisible(true);
    }//GEN-LAST:event_fundamentoselectronicaMouseClicked

    private void fundamentosingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fundamentosingMouseClicked
        InfoMateria info = new InfoMateria("Fundamentos de ingenieria ",this.nombre,this.idUsuario);
        info.setVisible(true);
    }//GEN-LAST:event_fundamentosingMouseClicked

    private void discretasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_discretasMouseClicked
        InfoMateria info = new InfoMateria("Matematicas discretas ",this.nombre,this.idUsuario);
        info.setVisible(true);
    }//GEN-LAST:event_discretasMouseClicked

    private void pensamientosistemicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pensamientosistemicoMouseClicked
        InfoMateria info = new InfoMateria("Pensamiento sistemico y sistematizacion ",this.nombre,this.idUsuario);
        info.setVisible(true);
    }//GEN-LAST:event_pensamientosistemicoMouseClicked

    private void ecuadiferencialesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ecuadiferencialesMouseClicked
        InfoMateria info = new InfoMateria("Ecuaciones diferenciales ",this.nombre,this.idUsuario);
        info.setVisible(true);
    }//GEN-LAST:event_ecuadiferencialesMouseClicked

    private void ingles3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingles3MouseClicked
        InfoMateria info = new InfoMateria("Ingles III ",this.nombre,this.idUsuario);
        info.setVisible(true);
    }//GEN-LAST:event_ingles3MouseClicked

    private void matespecialesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_matespecialesMouseClicked
        InfoMateria info = new InfoMateria("Matematicas especiales ",this.nombre,this.idUsuario);
        info.setVisible(true);
    }//GEN-LAST:event_matespecialesMouseClicked

    private void analisisnumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_analisisnumMouseClicked
        InfoMateria info = new InfoMateria("Analisis numerico ",this.nombre,this.idUsuario);
        info.setVisible(true);
    }//GEN-LAST:event_analisisnumMouseClicked

    private void artificialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_artificialMouseClicked
        InfoMateria info = new InfoMateria("Inteligencia artificial ",this.nombre,this.idUsuario);
        info.setVisible(true);
    }//GEN-LAST:event_artificialMouseClicked

    private void gerenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gerenciaMouseClicked
        InfoMateria info = new InfoMateria("Gerencia ",this.nombre,this.idUsuario);
        info.setVisible(true);
    }//GEN-LAST:event_gerenciaMouseClicked

    private void fisica3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fisica3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fisica3MouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Caldiferencial;
    private javax.swing.JLabel algebralineal;
    private javax.swing.JLabel analisisnum;
    private javax.swing.JLabel argumentativo;
    private javax.swing.JLabel arquitectura;
    private javax.swing.JLabel artificial;
    private javax.swing.JLabel automatas;
    private javax.swing.JLabel basesdedatos;
    private javax.swing.JLabel calintegral;
    private javax.swing.JLabel calmultivariado;
    private javax.swing.JLabel catedra;
    private javax.swing.JLabel cienciadedtaos;
    private javax.swing.JLabel cienciainnovacioncampo;
    private javax.swing.JLabel cienciainnovacionmarco;
    private javax.swing.JLabel ciudadania;
    private javax.swing.JLabel comudatos;
    private javax.swing.JLabel comunicacion2;
    private javax.swing.JLabel discretas;
    private javax.swing.JLabel ecuadiferenciales;
    private javax.swing.JLabel emprendimiento;
    private javax.swing.JLabel estadistica;
    private javax.swing.JLabel estructurasinfo;
    private javax.swing.JLabel fisica1;
    private javax.swing.JLabel fisica2;
    private javax.swing.JLabel fisica3;
    private javax.swing.JLabel fundamentosadmi;
    private javax.swing.JLabel fundamentoselectronica;
    private javax.swing.JLabel fundamentosing;
    private javax.swing.JLabel gerencia;
    private javax.swing.JLabel ingles1;
    private javax.swing.JLabel ingles2;
    private javax.swing.JLabel ingles3;
    private javax.swing.JLabel ingles4;
    private javax.swing.JLabel ingsoftware;
    private javax.swing.JLabel ingsoftware2;
    private javax.swing.JLabel innovacionpro;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel matespeciales;
    private javax.swing.JLabel modelacion;
    private javax.swing.JLabel networking;
    private javax.swing.JLabel opciongrado;
    private javax.swing.JLabel operativa;
    private javax.swing.JLabel operativos;
    private javax.swing.JLabel pensamientoal;
    private javax.swing.JLabel pensamientocri1;
    private javax.swing.JLabel pensamientosistemico;
    private javax.swing.JLabel planeacionestrategica;
    private javax.swing.JLabel profundizacion1;
    private javax.swing.JLabel profundizacion2;
    private javax.swing.JLabel programacion1;
    private javax.swing.JLabel programacion2;
    private javax.swing.JLabel redesycomunicacion;
    private javax.swing.JLabel seginformatica;
    private javax.swing.JLabel sisinformacion;
    // End of variables declaration//GEN-END:variables
}
